// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
import 'package:json_annotation/json_annotation.dart';
import 'package:api_provider/src/api_provider.dart' show JsonConvertable;

part 'example.g.dart';

@JsonSerializable()
class User extends JsonConvertable{
    int id;
    String name;
    String username;
    String email;
    Address address;
    String phone;
    String website;
    Company company;

    User({
        this.id,
        this.name,
        this.username,
        this.email,
        this.address,
        this.phone,
        this.website,
        this.company,
    });

    factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
    @override
    Map<String, dynamic> toJson() => _$UserToJson(this);

    @override
    JsonConvertable fromMap(Map<String, dynamic> json) => _$UserFromJson(json);
}

@JsonSerializable()
class Address {
    String street;
    String suite;
    String city;
    String zipcode;
    Geo geo;

    Address({
        this.street,
        this.suite,
        this.city,
        this.zipcode,
        this.geo,
    });

    factory Address.fromJson(Map<String, dynamic> json) => _$AddressFromJson(json);
    Map<String, dynamic> toJson() => _$AddressToJson(this);
}

@JsonSerializable()
class Geo {
    String lat;
    String lng;

    Geo({
        this.lat,
        this.lng,
    });

    factory Geo.fromJson(Map<String, dynamic> json) => _$GeoFromJson(json);
    Map<String, dynamic> toJson() => _$GeoToJson(this);
}

@JsonSerializable()
class Company {
    String name;
    String catchPhrase;
    String bs;

    Company({
        this.name,
        this.catchPhrase,
        this.bs,
    });
    factory Company.fromJson(Map<String, dynamic> json) => _$CompanyFromJson(json);
    Map<String, dynamic> toJson() => _$CompanyToJson(this);
}
